
server:
  port: 8081
spring:
  # astra
  data:
    cassandra:
      keyspace-name: main
      username: SPKGRnkEyaDdMsLGZZyfkehM
      password: -Eb.uhOfdDwcwI0Zot-DIPLEo4gt4rZWRnKOMnKJyoLq2UZPRXsW8Eea.sWT0RrmAI.w09zCe+ZZSjNPgR5e_,gMAJKfmqsnDQy.TwqkLFtL1b2lKnAlIXjH2y-avtIl
      schema-action: re-create
      request:
        timeout: 20s
      connection:
        connect-timout: 20s
        init-query-timeout: 20s

datastax.astra:
  secure-connect-bundle: secure-connect-tinher.zip
astra.db:
  id: e2c4752f-51f6-4102-b8c5-fa76fd6f64a8-1
  region: asia-south1
  keyspace: main
  application.token: AstraCS:SPKGRnkEyaDdMsLGZZyfkehM:48c64e143a2dc1d9ac64326d34a2b570ad6843acaae5530f54ea7502133eb53f



# application
tinhong:
  secret-key: colammoicoan